### ISSUE TITLE
Compatibility with ember 2.0 ?

### ISSUE THREAD

**Issue by vasilakisfil** [aexmachina/ember-devtools#13]
I tried to use thie wonderful addon in a fresh new ember 2.0.2 (ember-cli 1.3.7) project but as soon as I include it to the package.json I get this error:

Uncaught TypeError: Cannot read property 'map' of undefined, ember-devtools.js:6

Should it work ?

**Comment by aexmachina** [comment]
I've just pushed v4.0.0, which provides Ember 2 compatibility. Glad to know you appreciate the addon :+1:

**Comment by vasilakisfil** [comment]
Many thanks! Worked perfectly!
