### ISSUE TITLE
Cannot read property 'typeMaps' of undefined

### ISSUE THREAD

**Issue by OutOfNutella** [aexmachina/ember-devtools#14]
Hello !

I'm trying to use ember-devtools on my ember app.
I've added  this line to my package.json
`"ember-devtools": "^4.0.0"`

When I'm going to go on my app, I have the following error on my console
`Cannot read property 'typeMaps' of undefined`
on line 16 of ember-devtools.js, this line :
`this.typeMaps = this.store.typeMaps;`

It seems like the store isn't initialized or found.
I tried to use ember-devtools on another project, the embercli-todos project and ember-devtools worked perfectly.
I tried to search where does this error on my app come from but I unfortunately didn't found.

Have you ever met this error ? Have you any idea what i'm doing wrong ?

Here some other datas you could have need :
ember-cli version : 1.13.1
ember-devtools version : 4.0.0
ember-data version : 1.0.0-beta.19.2 

Thx for your answer.

**Comment by aexmachina** [comment]
What version of ember?​

**Comment by OutOfNutella** [comment]
I'm on the 1.13.1

**Comment by OutOfNutella** [comment]
I'm closing it cause it's nearly 2 years old
