### ISSUE TITLE
Expose version

### ISSUE THREAD

**Issue by zzarcon** [aexmachina/ember-devtools#22]
I create this as a proposal since I want to know your opinion about it first. So, I'd to have the version exposed into the global, something like `devTools.VERSION`.

What do you think? ^^

**Comment by aexmachina** [comment]
The version of what? The ember-devtools version or the app version?

**Comment by zzarcon** [comment]
Exactly, the version of ember-devtools, sorry I wasn't that clear ^^

**Comment by aexmachina** [comment]
A better source for that is `npm ls ember-devtools`. Anyway, it _should_ be transparent to the consumer of the package. So my opinion is that it's not necessary, unless there's a clear use case that would benefit from it. Feel free to reopen the issue.
