### ISSUE TITLE
Not working on Ember 2.5

### ISSUE THREAD

**Issue by vasilakisfil** [aexmachina/ember-devtools#23]
Hi.. thanks for the addon it is really good and when it's not there my ember coding is so miserable.

Unfortunately it doesn't play with Ember 2.5. When I open the console and I run one of the `route()`, `controller()` etc, I get `undefined`. I have setup a test ember app which you can investigate if you want:

https://github.com/vasilakisfil/ember-test

What could be the issue ?

**Comment by vasilakisfil** [comment]
This addon should really be officially supported.

**Comment by vasilakisfil** [comment]
It turns out that it doesn't work only if I have `global: true` whereas if I have a prefix it works fine. Probably something sneaky is going on in the `globalize` function.

**Comment by aexmachina** [comment]
Thanks for reporting. I just pushed a patch version that should fix that issue.
