### ISSUE TITLE
Maximum call stack exceeded when using ember-getowner-polyfill

### ISSUE THREAD

**Issue by espadrine** [aexmachina/ember-devtools#28]
The `if (Ember.getOwner) { // for ember > 2.3` check in [app/services/ember-devtools.js](https://github.com/aexmachina/ember-devtools/blob/master/app/services/ember-devtools.js#L15) doesn't take into account the possibility that some packages may use ember-getowner-polyfill, which fakes `Ember.getOwner` [here](https://github.com/rwjblue/ember-getowner-polyfill/blob/master/vendor/install-getowner-polyfill.js#L159). To compute it, it relies on `.container`, which ember-devtools computes from `Ember.getOwner`… which creates an infinite loop, resolved when the stack runs out.

Could we fix it by checking that `Object.getOwnPropertyDescriptor(_ember['default'], 'getOwner').get` is undefined before defining a fake .container in [app/services/ember-devtools.js](https://github.com/aexmachina/ember-devtools/blob/master/app/services/ember-devtools.js#L15)? (Honestly asking, I don't know enough to make sure that would work.)

**Comment by aexmachina** [comment]
Thanks for reporting the issue. I've published v6 with a fix. Note the [changelog](https://github.com/aexmachina/ember-devtools#changelog) for this version.

**Comment by espadrine** [comment]
Thanks a lot for fixing this issue! :kissing:
