### ISSUE TITLE
Questions: Production builds & supporting component(name)

### ISSUE THREAD

**Issue by patocallaghan** [aexmachina/ember-devtools#4]
Thanks for this addon, looks great. I have a few questions if you don't mind.

* How is this currently included in a project? If I add it to my project will this appear in the production `vendor.js` assets? If it does, can it be configured to only appear in development and testing?
* I notice you don't currently support `component(name)`, was there a reason for this and if not, would you be happy for me to submit a PR to support it?

**Comment by MiguelMadero** [comment]
re: components. 

I think it would probably nice to take a selector and return an array of needing in addition to using an id or DOM. I often find myself doing something like `devTools.view($('.ember-select')[3])`
