### ISSUE TITLE
Deprecation warning with Ember 1.12.0

### ISSUE THREAD

**Issue by aortbals** [aexmachina/ember-devtools#9]
https://github.com/aexmachina/ember-devtools/blob/master/app/initializers/ember-devtools.js#L11

should be:

```js
application.register('service:devtools', app.devTools);
```

This will also entail creating `Devtools` from within an Instance Initializer, I believe like this:

`instance-initializers/ember-devtools`:

```js
export default {
  name: 'ember-devtools',

  initialize: function(instance) {
    instance.devTools = Devtools.create({
      container: instance.container
    });
  }
};
```

I'm guessing to make this backwards compatible it would require a conditional in the standard initializer. I'm not sure if you even want to go down this route.

**Comment by Keeo** [comment]
:+1:

**Comment by aexmachina** [comment]
I've just pushed v4, which provides Ember 2.0 compatibility and should fix this problem. Enjoy!
